apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: myserver
spec:
  master:
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    basePlugins:
      - name: kubernetes
        version: 1.23.0
      - name: workflow-job
        version: "2.36"
      - name: workflow-aggregator
        version: "2.6"
      - name: git
        version: 4.0.0
      - name: job-dsl
        version: "1.76"
      - name: configuration-as-code
        version: "1.35"
      - name: configuration-as-code-support
        version: "1.19"
      - name: kubernetes-credentials-provider
        version: "0.13"
      - name: github-branch-source
        version: 2.6.0
      - name: jx-resources
        version: 1.0.38